'use client'

import { useState } from 'react'
import { ArrowRight, CheckCircle2, ChevronDown, Mail, Menu, ShieldCheck, X } from 'lucide-react'

const toc = [
  ['Waarom werkt mijn e-mail niet?', 'waarom'],
  ['Kan niet inloggen op mijn e-mail', 'inloggen'],
  ['E-mails komen niet binnen', 'ontvangen'],
  ['Ik kan geen e-mail versturen', 'versturen'],
  ['E-mail werkt niet op telefoon', 'telefoon'],
  ['E-mail werkt niet op computer', 'computer'],
  ['E-mail wachtwoord vergeten', 'wachtwoord'],
  ['E-mail foutmelding oplossen', 'foutmelding'],
  ['Wanneer moet ik contact opnemen met de Helpdesk?', 'helpdesk'],
  ['Veilig gebruik van E-mail Ondersteuning', 'veiligheid'],
  ['Veelgestelde vragen over E-mail Problemen', 'faq'],
]

const faqs = [
  ['Waarom werkt mijn e-mail vandaag niet?', 'Dit kan komen door een internetprobleem, storing, verkeerd wachtwoord, volle mailbox of een probleem met de e-mailapp. Controleer eerst uw verbinding en probeer opnieuw in te loggen.'],
  ['Wat moet ik doen als ik mijn e-mailwachtwoord vergeten ben?', 'Gebruik de officiële functie voor wachtwoordherstel van uw e-mailprovider. Deel uw herstelcode nooit met onbekende personen.'],
  ['Waarom ontvang ik geen e-mails?', 'Controleer de Spam-map, beschikbare opslagruimte, internetverbinding en instellingen van uw account. Vraag indien nodig officiële Hulp of Ondersteuning.'],
  ['Waarom kan ik geen e-mails versturen?', 'Controleer uw internetverbinding, het e-mailadres van de ontvanger en eventuele grote bijlagen. Test ook of een korte e-mail zonder bijlage wel wordt verzonden.'],
  ['Hoe vind ik het juiste Telefoonnummer van de Klantenservice?', 'Zoek het officiële Telefoonnummer via de officiële website of app van uw e-mailprovider. Gebruik niet zomaar een Nummer van een onbekende website.'],
  ['Kan de Helpdesk mijn wachtwoord zien?', 'Een betrouwbare officiële Helpdesk hoort niet om uw volledige wachtwoord of persoonlijke verificatiecode te vragen. Gebruik alleen veilige herstelmethoden.'],
  ['Mijn e-mail werkt niet op mijn telefoon. Wat kan ik doen?', 'Controleer WiFi of mobiele data, update de app, start uw telefoon opnieuw op en controleer of uw account via de officiële website werkt.'],
]

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-28 border-t border-border py-12 md:py-16"><h2 className="max-w-3xl text-2xl font-semibold tracking-tight text-foreground md:text-3xl">{title}</h2><div className="mt-5 max-w-3xl space-y-5 text-[17px] leading-8 text-muted-foreground">{children}</div></section>
}

function BulletList({ items }: { items: string[] }) {
  return <ul className="space-y-3">{items.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 size-5 shrink-0 text-primary" aria-hidden="true" /><span>{item}</span></li>)}</ul>
}

export default function Page() {
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [menuOpen, setMenuOpen] = useState(false)

  return <main className="min-h-screen bg-background">
    <header className="sticky top-0 z-50 border-b border-border/80 bg-background/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8">
        <a href="#top" className="flex items-center gap-3" aria-label="E-mail Hulp Nederland home"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Mail className="size-5" aria-hidden="true" /></span><span className="text-sm font-bold tracking-tight md:text-base">E-mail Hulp Nederland</span></a>
        <nav className="hidden items-center gap-8 text-sm font-medium text-muted-foreground md:flex"><a href="#oplossingen" className="transition-colors hover:text-primary">Oplossingen</a><a href="#veiligheid" className="transition-colors hover:text-primary">Veiligheid</a><a href="#faq" className="transition-colors hover:text-primary">Veelgestelde vragen</a></nav>
        <button className="rounded-lg p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu openen" aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button>
      </div>
      {menuOpen && <nav className="flex flex-col gap-4 border-t border-border px-5 py-4 text-sm font-medium md:hidden"><a href="#oplossingen" onClick={() => setMenuOpen(false)}>Oplossingen</a><a href="#veiligheid" onClick={() => setMenuOpen(false)}>Veiligheid</a><a href="#faq" onClick={() => setMenuOpen(false)}>Veelgestelde vragen</a></nav>}
    </header>

    <div id="top" className="border-b border-border bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="max-w-4xl"><p className="mb-6 flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.18em] text-primary-foreground/70"><span className="size-2 rounded-full bg-accent" /> Onafhankelijke hulp en ondersteuning</p><h1 className="text-balance text-4xl font-semibold leading-tight tracking-[-0.03em] md:text-6xl">E-mail Werkt Niet?<br /><span className="text-primary-foreground/65">E-mail Hulp, Helpdesk en Ondersteuning in Nederland</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-primary-foreground/75">Werkt uw e-mail niet? Lees oplossingen voor e-mailproblemen, inloggen, wachtwoorden en berichten ontvangen met handige hulp en ondersteuning in Nederland.</p><a href="#oplossingen" className="mt-9 inline-flex items-center gap-2 rounded-lg bg-accent px-5 py-3.5 text-sm font-bold text-accent-foreground transition-transform hover:-translate-y-0.5">Bekijk oplossingen <ArrowRight className="size-4" /></a></div></div></div>

    <div id="oplossingen" className="mx-auto grid max-w-7xl gap-12 px-5 py-12 md:grid-cols-[240px_1fr] md:px-8 md:py-20">
      <aside className="hidden md:block"><div className="sticky top-28"><p className="mb-5 text-xs font-bold uppercase tracking-[0.16em] text-primary">Op deze pagina</p><nav className="space-y-3 border-l border-border pl-4 text-sm leading-5 text-muted-foreground">{toc.map(([label, id]) => <a key={id} href={`#${id}`} className="block transition-colors hover:text-primary">{label}</a>)}</nav></div></aside>
      <article>
        <div className="mb-12"><p className="text-sm font-semibold text-primary">Praktische gids</p><h2 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">E-mail werkt niet? Veelvoorkomende problemen en oplossingen</h2><p className="mt-5 max-w-3xl text-[17px] leading-8 text-muted-foreground">E-mail is voor veel mensen belangrijk voor werk, school, online accounts en contact met familie en vrienden. Daarom kan het erg vervelend zijn wanneer uw e-mail niet werkt. Misschien kunt u niet inloggen, ontvangt u geen nieuwe berichten of lukt het niet om een e-mail te verzenden. Soms verschijnt er ook een foutmelding.</p><p className="mt-5 max-w-3xl text-[17px] leading-8 text-muted-foreground">In dit artikel leest u meer over veelvoorkomende e-mailproblemen, mogelijke oorzaken en eenvoudige oplossingen. U vindt ook informatie over Helpdesk, Klantenservice, Telefoonnummer, Hulp, Nummer en Ondersteuning in Nederland.</p></div>
        <Section id="waarom" title="Waarom werkt mijn e-mail niet?"><p>Er kunnen verschillende redenen zijn waarom een e-mailaccount problemen geeft. Een veelvoorkomend probleem is een onjuist wachtwoord. Het is ook mogelijk dat de internetverbinding niet goed werkt.</p><p>Andere mogelijke oorzaken zijn:</p><BulletList items={['Onjuist e-mailadres of wachtwoord','Problemen met de internetverbinding','Volle mailbox of onvoldoende opslagruimte','Verouderde e-mailapp','Problemen met browser, cookies of cache','Onjuiste serverinstellingen','Tijdelijke storing bij de e-maildienst','Beveiligingscontrole van uw account']} /><p>Wanneer u niet zeker weet wat het probleem veroorzaakt, kunt u stap voor stap controleren waar de fout zit.</p></Section>
        <Section id="inloggen" title="Kan niet inloggen op mijn e-mail"><p>Een van de meest voorkomende problemen is dat gebruikers niet kunnen inloggen. Controleer eerst of u het juiste e-mailadres invoert. Let ook goed op hoofdletters, cijfers en speciale tekens in uw wachtwoord.</p><p>Wanneer u uw wachtwoord bent vergeten, gebruik dan alleen de officiële optie voor wachtwoordherstel van uw e-mailprovider. Deel uw wachtwoord of verificatiecodes nooit met onbekende personen.</p><p>Als het probleem blijft bestaan, kunt u contact opnemen met de officiële Klantenservice of Helpdesk van uw e-mailprovider voor veilige Hulp en Ondersteuning.</p></Section>
        <Section id="ontvangen" title="E-mails komen niet binnen"><p>Ontvangt u geen nieuwe e-mails? Controleer dan eerst uw internetverbinding. Open daarna uw inbox opnieuw en kijk ook in de map Spam, Ongewenste e-mail of Prullenbak.</p><p>Soms worden belangrijke berichten per ongeluk gefilterd. Controleer daarom ook uw e-mailregels en instellingen.</p><p>Controleer daarnaast of uw mailbox voldoende vrije ruimte heeft. Wanneer de opslagruimte vol is, kunnen nieuwe berichten mogelijk niet correct worden ontvangen.</p><p>Dit probleem kan vaak worden opgelost door:</p><ol className="list-decimal space-y-3 pl-6 marker:font-semibold marker:text-primary"><li>Spam en ongewenste berichten te controleren.</li><li>Oude e-mails en grote bijlagen te verwijderen.</li><li>De internetverbinding opnieuw te starten.</li><li>De e-mailapp te sluiten en opnieuw te openen.</li><li>De browsercache en cookies te wissen.</li><li>Opnieuw in te loggen op uw account.</li></ol><p>Voor aanvullende E-mail Hulp Nederland kunt u de officiële ondersteuningspagina van uw provider gebruiken.</p></Section>
        <Section id="versturen" title="Ik kan geen e-mail versturen"><p>Soms kunt u wel e-mails ontvangen, maar niet verzenden. Dit kan gebeuren door een slechte internetverbinding, een probleem met de uitgaande server of een grote bijlage.</p><p>Probeer eerst een korte testmail zonder bijlage te versturen. Werkt dit wel? Dan kan de grootte of het bestandstype van de bijlage het probleem veroorzaken.</p><p>Controleer ook of het e-mailadres van de ontvanger correct is geschreven. Een kleine fout in het adres kan ervoor zorgen dat het bericht niet wordt bezorgd.</p><p>Blijft het probleem bestaan, controleer dan de officiële instellingen of vraag technische Ondersteuning aan bij de betreffende e-maildienst.</p></Section>
        <Section id="telefoon" title="E-mail werkt niet op telefoon"><p>Veel gebruikers ervaren problemen met e-mail op een smartphone of tablet. De e-mailapp kan bijvoorbeeld geen verbinding maken met de server of steeds om een wachtwoord vragen.</p><p>Probeer de volgende stappen:</p><BulletList items={['Controleer of WiFi of mobiele data werkt.','Start de telefoon opnieuw op.','Update de e-mailapp.','Controleer de datum en tijd van het apparaat.','Verwijder en voeg het e-mailaccount opnieuw toe, als dat veilig en nodig is.','Controleer of het account via de officiële website wel werkt.']} /><p>Als uw account online wel werkt, maar niet in de app, ligt het probleem mogelijk bij de app of apparaatinstellingen.</p></Section>
        <Section id="computer" title="E-mail werkt niet op computer"><p>Wanneer uw e-mail op een computer niet goed werkt, kan het probleem worden veroorzaakt door de browser. Oude cookies, cachebestanden of browserextensies kunnen soms storingen veroorzaken.</p><p>Probeer daarom:</p><BulletList items={['Een andere browser.','Een privévenster.','Cookies en cache verwijderen.','Browserextensies tijdelijk uitschakelen.','De browser opnieuw starten.','Uw computer opnieuw opstarten.']} /><p>Controleer daarna opnieuw of u kunt inloggen en berichten kunt verzenden of ontvangen.</p></Section>
        <Section id="wachtwoord" title="E-mail wachtwoord vergeten"><p>Bent u uw e-mailwachtwoord vergeten? Gebruik dan de officiële pagina voor wachtwoordherstel. Meestal moet u uw identiteit bevestigen via een herstelmethode die eerder aan uw account is gekoppeld.</p><p>Maak na herstel een sterk wachtwoord. Gebruik bij voorkeur een unieke combinatie die u niet voor andere accounts gebruikt. Schakel ook tweestapsverificatie in wanneer deze beschikbaar is.</p><p><strong>Let op:</strong> een echte Klantenservice zal normaal gesproken niet zomaar vragen om uw volledige wachtwoord. Geef nooit uw wachtwoord, herstelcode of beveiligingscode aan onbekende personen.</p></Section>
        <Section id="foutmelding" title="E-mail foutmelding oplossen"><p>Een foutmelding kan verschillende oorzaken hebben. Lees de melding zorgvuldig voordat u actie onderneemt. Noteer eventueel de foutcode en zoek deze op via de officiële documentatie van uw e-mailprovider.</p><p>Veel voorkomende meldingen hebben te maken met:</p><BulletList items={['Onjuiste inloggegevens','Geen internetverbinding','Serverproblemen','Onvoldoende opslagruimte','Onjuiste beveiligingsinstellingen','Problemen met synchronisatie']} /><p>Door de exacte foutmelding te controleren, kunt u gerichter Hulp en Ondersteuning vinden.</p></Section>
        <Section id="helpdesk" title="Wanneer moet ik contact opnemen met de Helpdesk?"><p>U kunt contact opnemen met de officiële Helpdesk of Klantenservice wanneer eenvoudige oplossingen niet werken. Dit is vooral belangrijk wanneer u denkt dat uw account is geblokkeerd, gehackt of zonder uw toestemming is gewijzigd.</p><p>Zoek het officiële Telefoonnummer of contactkanaal altijd via de website of app van uw eigen e-mailprovider. Controleer goed of u werkelijk met de juiste organisatie contact opneemt.</p><p>Gebruik geen willekeurig Nummer dat u in een advertentie, onbekende website of pop-up ziet. Dit helpt u om fraude en ongewenste toegang tot uw account te voorkomen.</p></Section>
        <Section id="veiligheid" title="Veilig gebruik van E-mail Ondersteuning"><div className="rounded-2xl bg-secondary p-6 md:p-8"><div className="flex gap-4"><ShieldCheck className="size-7 shrink-0 text-primary" aria-hidden="true" /><div><p className="font-semibold text-foreground">Bescherm uw gegevens</p><p className="mt-2">Wanneer u online zoekt naar E-mail Helpdesk Nederland, Klantenservice E-mail, E-mail Telefoonnummer, E-mail Hulp of Technische Ondersteuning, kunnen veel verschillende websites verschijnen.</p></div></div><p className="mt-7">Voor uw veiligheid is het verstandig om:</p><div className="mt-4"><BulletList items={['Alleen officiële websites te gebruiken.','Geen wachtwoorden telefonisch door te geven.','Geen verificatiecodes met onbekenden te delen.','Geen onbekende software te installeren.','Geen externe persoon zomaar toegang tot uw computer te geven.','Het officiële contactnummer van de provider te controleren.']} /></div><p className="mt-6">Legitieme ondersteuning kan u helpen met technische problemen, maar uw persoonlijke beveiligingsgegevens moeten beschermd blijven.</p></div></Section>
        <Section id="faq" title="Veelgestelde vragen over E-mail Problemen"><div className="divide-y divide-border border-y border-border">{faqs.map(([question, answer], index) => <div key={question}><button className="flex w-full items-center justify-between gap-5 py-5 text-left font-semibold text-foreground" onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index}>{index + 1}. {question}<ChevronDown className={`size-5 shrink-0 text-primary transition-transform ${openFaq === index ? 'rotate-180' : ''}`} /></button>{openFaq === index && <p className="pb-5 pr-8 text-base leading-7">{answer}</p>}</div>)}</div></Section>
        <Section id="conclusie" title="Conclusie"><p>Wanneer uw e-mail niet werkt, hoeft het probleem niet altijd ernstig te zijn. In veel gevallen kan een controle van uw internetverbinding, wachtwoord, browser, app of opslagruimte het probleem oplossen.</p><p>Heeft u nog steeds problemen met inloggen, e-mails ontvangen of berichten versturen? Zoek dan naar de officiële Helpdesk, Klantenservice, Telefoonnummer, Hulp en Ondersteuning in Nederland van uw specifieke e-mailprovider.</p><p>Gebruik altijd officiële contactkanalen en bescherm uw wachtwoord, verificatiecodes en persoonlijke gegevens. Zo kunt u uw e-mailprobleem zo veilig mogelijk oplossen.</p></Section>
      </article>
    </div>
    <footer className="border-t border-border bg-secondary"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-muted-foreground md:flex-row md:items-center md:justify-between md:px-8"><span className="font-semibold text-foreground">E-mail Hulp Nederland</span><span>Veilige, praktische informatie over e-mailproblemen.</span></div></footer>
  </main>
}

